Added Mode.java
AkMo3/DSA-Java pull request #60
Opened 2020-12-10 03:56 UTC by KostasThan

### **Describe your change:**
Fixes: #46 
- [x] Add an Algorithm?
- [ ] Add a Data Structure?
- [ ] Add a Program not related to above?
- [ ] Fix a bug or typo in an existing cases?
- [ ] Documentation change?

#### References

### **Checklist:**

- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-12-10 14:56 UTC, AkMo3 requested changes
Great Work, just a small recommendation.

2020-12-10 14:56 UTC, AkMo3 commented on Misc/Mode.java
> +    HashMap<E, Integer> appCounter = new HashMap<>();
It could be better if you change the name of hashMap to something else like freqCounter, so it clearly indicates it calculates frequency.

2020-12-10 16:21 UTC, KostasThan commented
Yeah, you are right, but how should i do that without messing the PR? 😅

2020-12-10 17:12 UTC, AkMo3 commented
Just do changes on your current branch, and push them. The changes will automatically get add here.

2020-12-11 14:07 UTC, AkMo3 approved these changes

2020-12-11 14:08 UTC, merged